### ISSUE TITLE
guards (colon style if)

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#100]
```
      fib←{(⍵=1)∨⍵=2:1 ⋄ (fib (⍵-2))+fib (⍵-1)}
      fib¨⍳7
1 1 2 3 5 8 13
```

```
APRIL> (april "fib←{$[(⍵=1)∨⍵=2:1 ⋄ (fib (⍵-2))+fib (⍵-1)]}")
#<FUNCTION (LAMBDA (⍵ &OPTIONAL ⍺)) {5318578B}>
APRIL> (april "fib¨⍳7")
#(NIL NIL NIL NIL NIL NIL NIL)
APRIL>
```

i know april has the k-style... but if this isn't too much trouble to add it would help with porting from dyalog.

also discussed in #99 

they look straight forward?
https://help.dyalog.com/18.0/Content/Language/Defined%20Functions%20and%20Operators/DynamicFunctions/Guards.htm#Guards

**Comment by phantomics** [comment]
I don't like the Dyalog-style guard that much because it's an exception to the rules for handling `⋄` or a line break. Normally line breaks are handled by the parser at a low level, but when guards enter the picture suddenly a line may not be evaluated depending on what happens after the guard. The implementation of `$` is much more internally consistent; the contents of the axes preceding it are processed by a function generating a CL if-statement. Same reason I changed the way `[→ branch]` works; the standard implementation breaks APL grammar convention by having a functional character with a left argument but none on the right.

**Comment by justin2004** [comment]
ah, i see.
thanks for the explanation. 

no worries. when porting dyalog to april converting guards to k-style is easy anyway.
