### ISSUE TITLE
assign the result of selective assignment

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#103]
i don't have any immediate need for this behavior but i thought i'd note it for the sake of completeness.

```
      a←⍳5
      newa←(3⊃a)←30
      newa
30
      a
1 2 30 4 5
```

```
APRIL> (april "a←⍳5")
#(1 2 3 4 5)
APRIL> (april "newa←(3⊃a)←30")
The function COMMON-LISP:NIL is undefined.
   [Condition of type UNDEFINED-FUNCTION]
```

**Comment by phantomics** [comment]
Good find, I'm working on some optimizations now and returning to other issues once that's done. I also wanted to give you a heads-up since I haven't seen you in chat: there is a Kenneth Iverson centenary event happening tomorrow hosted by Roger Hui, Morten Kromberg and Arthur Whitney. These are some of the most important people in vector language history and you'd probably like to attend given your interest in APL. You can sign up here: https://www.eventbrite.co.uk/e/ken-iverson-centenary-tickets-132578131761

There's a limited number of seats so register soon.

**Comment by justin2004** [comment]
thanks for the heads-up! i registered.

**Comment by phantomics** [comment]
This is now working. Give it a try.
