### ISSUE TITLE
enlist -- after a selfie that returns a matrix

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#106]
```
      ∘.+⍨10 2
20 12
12  4
      ∊∘.+⍨10 2
20 12 12 4
```

```
CL-USER> (april "∘.+⍨10 2")
#2A((20 12) (12 4))
CL-USER> (april "∊∘.+⍨10 2")
(SB-C::XEP (LAMBDA (A O))) called with invalid number of arguments: 1
```

but if you add some parens:
```
CL-USER> (april "∊(∘.+⍨10 2)")
#(20 12 12 4)
```

**Comment by phantomics** [comment]
The issue here is the same as the problem [you found here](https://github.com/phantomics/april/issues/116). It's about how the parser handles function definitions after a pivotal operator like `.`. These bugs are highlighting some weaknesses in the current parser system, and I've been thinking for some time that the parser needs substantial reworking so that'll be the solution for this. It'll take a while though, I've just made a big change correcting the nested array model and a revamp of the parser will be the next big goal.

**Comment by phantomics** [comment]
This has been fixed by the same feature in the new parser that fixed the other issue I linked to above.
