### ISSUE TITLE
selective assignment with squad

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#115]
```
      m←4 4 ⍴ ⍳ 4
      (2 2 ⌷m)←99
      m
1  2 3 4
1 99 3 4
1  2 3 4
1  2 3 4
```

```
APRIL> (april "m←4 4 ⍴ ⍳ 4")
#2A((1 2 3 4) (1 2 3 4) (1 2 3 4) (1 2 3 4))
APRIL> (april "(2 2 ⌷m)←99")
NIL
APRIL> (april "m")
NIL
```

**Comment by phantomics** [comment]
Good find, this was happening because of a bug with the assignment logic; in cases when the array was compatible with the value to be assigned, the original array itself would be changed instead of a copy being created; in this case there was no return value from the assignment function, but the implementation expected one so nil got returned instead. This is now controlled for.
