### ISSUE TITLE
Implement native file operations 

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#124]
Please implement native file operations - ⎕NTIE, ⎕UNTIE, ⎕NREAD.

**Comment by justin2004** [comment]
is a "native file" just a file in the file system? if so i thought that was part of the value of implementing an APL in CL -- so you don't have to implement utility function like that? that is, some CL has all the file interaction functionality.

**Comment by phantomics** [comment]
Can you tell me a bit more about the use case you're thinking about here? As Justin said, my intention with April has been to offload these kind of system interactions to CL. Using `⎕NTIE` and `⎕UNTIE` in APL is clumsier than using a `(with-open-file)` closure in Lisp, since the latter automatically closes the file upon leading the body. 

The `⎕NREAD` syntax is likewise clunky, revealing some of APL's syntactic shortcomings, compared to using something like the lisp-binary library. The data you read from a file can easily be passed into April using `(april-c)`. I could consider doing something like this if there's a really compelling use case, but there's probably another way. 

If you want to write an array processing function that's capable of opening files depending on something it does with array contents, you can import an arbitrary Lisp function into April by using the `(april (with (:store-fun (lambda (omega) ...do stuff...)) "apl code")` syntax. Let me know.

**Comment by egao1980** [comment]
Thanks for the clarification. I think :store-fun solution is good.
