### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#138]
"If you use dashes in the names of Lisp variables you pass into April, note that inside April they will be converted to camel case."

could you also add a note to the effect... "even though APL respects case in variable names (:store-fun) will not respect case."

e.g.
```
APRIL> (april (with (:store-fun (iD #'identity)) )
         "iD 4")
The function APRIL-WORKSPACE-COMMON::|iD| is undefined.
   [Condition of type UNDEFINED-FUNCTION]
```

not even the pipes will help you:
```
(april (with (:store-fun (|iD| #'identity)) )
         "iD 4"
The function APRIL-WORKSPACE-COMMON::|iD| is undefined.
   [Condition of type UNDEFINED-FUNCTION]         
```

**Comment by phantomics** [comment]
I could set it up so that pipe-quoted variable names will be imported with the case preserved as long as there are no dashes in the name. How does that sound? Of course, you can also store `iD` as `i-d` in order to get the capitalization you want, but that gets annoying if you want capitals in sequence as with `parse-j-s-o-n` for `parseJSON`.

**Comment by justin2004** [comment]
that sounds good. and it would be the exception that proves the rule (the rule that store-fun does not respect your case)  in the documentation.

**Comment by phantomics** [comment]
You can now store literal function or variable names by passing them as strings. For example:

```lisp
(april (with (:store-fun ("aBcDe" (lambda (x) (+ x 10))))) "aBcDe 5")
15
```

The reason for using strings instead of pipe-quoted symbols is that CL can't tell the difference between a symbol entered as `ABC` and `|ABC|`, so the latter will be counter-intuitively converted to lowercase. String symbol names will cause an error if they contain a dash or other illegal character, this is described in the docs now.
