### ISSUE TITLE
Missing axes support for scalar dyadic operators 

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#16]
```apl
 (2 3⍴5)+[2] 1 2 3
6 7 8
6 7 8
```

In April:

```lisp
CL-USER> (april:april-c " (2 3⍴5)+[2] 1 2 3")
; Debugger entered on #<SIMPLE-ERROR "Array size mismatch." {100542F6A3}>
```

The fix should be relatively straightforward by changing ```apply-scalar``` signature to ```(defun apply-scalar (function alpha &optional omega axes is-boolean) ...)``` and supporting application along the axis.

**Comment by egao1980** [comment]
I'm trying to make some image manipulation code work, here is an example luminocity-based grayscale conversion ```{+/[3]⍵×[3]0.2989 0.5870 0.1141}```.

**Comment by phantomics** [comment]
Interesting, somehow I never heard about using axes with scalar APL functions before. I'll add this, but it will be a bit complicated because the (apl-call) macro will have to be modified to support composing scalar functions with axes, among other changes.

In the meantime, you can accomplish what you're trying to do by using the `[⍤ rank]` operator. Like this:

```apl
      (2 3⍴5)+⍤1⊢1 2 3
6 7 8
6 7 8
```

It treats the left argument as though it were a pair of 3-element vectors (thus decomposing it into rank 1 vectors) , adds each vector to the right argument, and then re-merges the vectors into the 2x3 matrix.

**Comment by egao1980** [comment]
Actually your code already handles it just fine in case of , (ravel/catenate/laminate) for example. Axes in dyadic functions are parsed correctly and are sent to```apply-scalar```, that's why I proposed moving internal ```is-boolean``` and adding ```axes``` before it.

**Comment by egao1980** [comment]
I've checked Dyalog and GNU APL and both have this.

**Comment by phantomics** [comment]
Just added it, give it a try.

**Comment by egao1980** [comment]
Thanks a lot. It works fine. Usable speed, though we'd need to optimize it later.
