### ISSUE TITLE
print order appears non-deterministic

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#170]
```
FLAMEGRAPH> (april "f←{⎕←⍵ ⋄ ⍵} ⋄ f\\1 2 3")
3
3
2
#(1 2 3)
FLAMEGRAPH> (april "f←{⎕←⍵ ⋄ ⍵} ⋄ f\\1 2 3")
2
3
3
#(1 2 3)
FLAMEGRAPH> (april "f←{⎕←⍵ ⋄ ⍵} ⋄ f\\1 2 3")
3
23

#(1 2 3)
```

whereas dyalog's print order is stable
```
      f←{ ⎕←⍵ ⋄ ⍵} ⋄ f\ 1 2 3
2
3
3
1 2 3
```

**Comment by phantomics** [comment]
This happens because the operation is run multithreaded, not synchronously. I'm considering how to proceed here.

**Comment by justin2004** [comment]
for debugging -- is it possible to prefix printing with a logical sequence number?

e.g.
instead of
```
3
3
2
```

```
seq 2:3
seq 1:3
seq 0:2
```

and if people want to use ⎕← for stable formatted output i bet there is another method they could use for stability.

**Comment by phantomics** [comment]
I've put an interim solution in place: the operators now all run single-threaded. This will of course cause a performance hit but it's the only way

The longer-term solution for after the next release will be to set up a system that analyzes functions to find side effects and allows operators to run in parallel with functions that have no side effects; basically, this means not assigning variables that aren't local to the function and not using functions that do. Stay tuned for more progress on this.

**Comment by phantomics** [comment]
At long last, just over a year since this was opened, multithreaded operators are back. A side effect accounting system is now in place to check functions being compiled for side effects. These mainly come in the form of `⎕←` to print arrays as in the bug report example above and non-lexical assignments of variables by function, i.e. `a+←5` or `b⊢←3`. Functions with side effects will be applied synchronously by the operators, while functions without side effects can be run in parallel.
