### ISSUE TITLE
Inclusion of maxpc

### ISSUE THREAD

**Issue by quicklisp** [phantomics/april#185]
Why does this project include maxpc instead of just referencing it?

**Comment by phantomics** [comment]
MaxPC is AGPL-licensed, but Max created an Apache-licensed snapshot for me to use within April. April now includes that snapshot so there are no problems with conflicting licenses.

**Comment by quicklisp** [comment]
This causes problems with conflicting systems in Quicklisp. I can't include April if it includes the system named "maxpc."

**Comment by phantomics** [comment]
As far as I know I changed the name of the system to `maxpc-apache` in its .asd file and the .asd files that depend on it. I found that there was a maxpc.asd file remaining in the folder and removed it, I also changed the name of the test system to `maxpc-apache-test`. I just pushed a commit with those changes, do they affect the problem you're seeing? Thanks.

**Comment by justin2004** [comment]
i just pulled master and when i 
```
(ql:quickload 'april)
```

i get

```
To load "april":
  Load 1 ASDF system:
    april
; Loading "april"

debugger invoked on a QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread
#<THREAD "main thread" RUNNING {1001890213}>:
  System "maxpc-apache" not found
```

**Comment by phantomics** [comment]
That's not good. By any chance do you have April linked from your `~/quicklisp/local-projects` directory? I've found that sometimes adding new systems in subfolders of April's repo will result in them not being recognized until you delete the link and add it again. Otherwise I'll need to check into this, the maxpc-apache system shouldn't be handled any differently than aplesque or vex.

**Comment by justin2004** [comment]
i don't have any symlinks involved. the april git repo lives here:
/home/justin/quicklisp/local-projects/april

ok, i got it to load by doing:
```
(push #p"/mnt/maxpc-apache/" asdf:*central-registry*)
```

i always run sbcl in a docker container so /mnt in the container is really /home/justin/quicklisp/local-projects/april in the host.

does emacs put your `pwd` in asdf:*central-registry* ?

**Comment by justin2004** [comment]
oh, this could be related...

for me:
```
CL-USER> asdf:*central-registry*
(#P"/home/containeruser/quicklisp/quicklisp/")
```

but i think it maybe should be:
home/containeruser/quicklisp/


because local-projects is not in /home/containeruser/quicklisp/quicklisp/
it is in
/home/containeruser/quicklisp/

what is your `asdf:*central-registry*` ?

**Comment by phantomics** [comment]
My ` asdf:*central-registry*` is `/home/phantomics/quicklisp/quicklisp`. I have my April directory symlinked from local-projects. I find that sometimes when I add directories containing new ASDF systems, they aren't recognized by asdf until I erase that symlink and recreate it.

Could you try setting up another April in an unused location and see how that works? That's always worked fine for me.

By the way, there's a surprise for you in [the array function demo](https://github.com/phantomics/april/blob/master/demos/dfns/array/array.apl). Give it a try.

**Comment by justin2004** [comment]
wow, did you port display!?
i remember thinking that would be tricky!

**Comment by phantomics** [comment]
Yes, there were a couple changes I had to make. I removed the error guard (the line with `16::`) because April doesn't handle errors that way and because that line is meant to catch instances of objects and other unprintable things that can't be created within April as opposed to Dyalog. I changed the line that's used to make an underline on characters because my type-checking is different from Dyalog's. The other difference you may notice is that I reordered the utility functions within the display function. That's because April needs each function to be defined before another function is defined that uses it, otherwise it doesn't know that the function's symbol represents a function.

In other news, I heard from Zach that April is now building correctly so I'll be closing this issue.
