### ISSUE TITLE
optimization question: discarding intermediate information because you have the end in sight

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#193]
In the following expression we can see we don't need to compute the intermediate value -24 because in the end we just want the sign.
```
APRIL> (april "××/ 2 ¯2 6")
-1
```

So we can substitute in this less expensive expression:
```
APRIL> (april "×/× 2 ¯2 6")
-1
``` 

And it does make a run time difference for some inputs:
```
APRIL> (april "num←100000 ⋄ size←100000 ⋄ v←(?num ⍴ size) - (size÷2) ⋄ 0")
0
APRIL> (april "vv←(0≠v)/v⋄0")    ; remove zeros so we don't get a short circuit
0
APRIL> (time (april "×/× vv"))
Evaluation took:
  0.012 seconds of real time
  0.025116 seconds of total run time (0.024377 user, 0.000739 system)
  208.33% CPU
  31,884,923 processor cycles
  5,615,712 bytes consed
  
1
APRIL> (time (april "××/ vv"))
Evaluation took:
  5.144 seconds of real time
  5.520601 seconds of total run time (5.237556 user, 0.283045 system)
  [ Run times consist of 1.012 seconds GC time, and 4.509 seconds non-GC time. ]
  107.33% CPU 
  11,809,518,567 processor cycles
  13,264,321,312 bytes consed
  
1
```

Can April do that substitution for this pattern?

Also could April do general substitutions like that for more than just this pattern?
I think looking at the final function isn't always enough. April might also need a system of noting information loss per function (kind of like it does for noting function inverses). 
e.g. 
For monadic `×` (-infinity,0) is -1, 0 is 0, (0, +infinity) is 1. the magnitude relative to 0 (inclusive) is lost but the direction is retained. 
For monadic `3∘<`  (-infinity, 3] is 0 and (3, +infinity) is 1. the magnitude relative to 3 (exclusive) is lost but the direction is retained.

And then April might need an algebra for combining information loss per function. If it applies that algebra (from left to right -ish) it can discard unneeded intermediate information along the the way...
or reorder to prevent unneeded intermediate information from being produced...

**Comment by phantomics** [comment]
I've given considerable thought to what you describe. It's a kind of lazy evaluation. Clearly, some operations can be simplified if you know what their results will later be used for. For example, if you have a 1000x1000 matrix M, in the case of `5 5↑20⌽M`, you shouldn't need to do the rotation for all million elements if you know the result is getting cut down to 5 x 5. If you just find which pre-rotated elements will fall into that 5x5 section, you can compute for only those elements.

A strategy I've considered for this would be to have array operations return, instead of a value, a function that may be evaluated to produce the result of the array operation but can be called with other arguments to add to the parameters of the array operation. In the example above, `20⌽M` would return a function that if invoked with no arguments would return the rotated array, but it could also be called with parameters that would express things like "the result will have a 5x5 take applied", and then when the function is invoked, that parameter would cause only the rotated output for the upper left 5x5 to be computed. In the case of an intermediate function passed to an operation that can't use it, it would be evaluated and the expected output value would result.

This is a complex combinatoric problem and would represent an ambitious step for April, so don't expect to see anything like this soon. For now the priority is the release, but it would be a fascinating addition.

**Comment by justin2004** [comment]
I listened to an episode of The Array Cast the other day and the guest (a developer of the J language implementation) talked about some work he did as a consultant... adding parallelization to some composite functions. He said in those cases what is returned is a nested scalar (that is wrapped in a Future). When you disclose it either blocks (while the value is being computed) or returns the value.

It does seems like laziness could work for your example (where you only want a tiny submatrix from a large matrix). 
But for my example laziness would only defer the computation of -24. To not produce -24 it seems like we'd have to detect that the outer direction function doesn't need any magnitude information from the inner multiplication reduction and have the inner multiplication reduction re-arrange itself accordingly.

Agreed, I don't expect to see this in April anytime soon but I thought it would be fun to talk it out.

**Comment by justin2004** [comment]
i ran this idea by [henry rich](https://github.com/HenryHRich) and he thinks that detecting cases like this would be difficult and not worth the payoff on average. he said he thinks the programmer with a profiler is where we are right now. :) 

so i think we can close this.
