### ISSUE TITLE
string vs. vector with a single char

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#198]
```
      ('a',⍬)≡1↑'amy'
1
```

```
APRIL> (april "1↑'amy'")
"a"
APRIL> (april "('a',⍬)")
#(#\a)
```
trouble is brewing...
```
APRIL> (april "('a',⍬)≡1↑'amy'")
0
```

**Comment by phantomics** [comment]
This is fixed. Two changes have been made: comparing `#(#\a)` and `"a"` with `≡` will now produce 1, since both arrays contain a character element. Also, `'a',⍬` will now produce `"a"`. However, there will still be cases where array transformations applied to a pure character array will produce a t-type array like `#(#\a)`. It's hard to account for all of these cases and ensure that an all-character output array will not be t-type, since it can necessitate expensive checks of array element types. Let me know if you find more issues of this type, eventually there may be a need for a broader solution.

**Comment by justin2004** [comment]
>It's hard to account for all of these cases and ensure that an all-character output array will not be t-type

would it be easier to just always work with t-type arrays?

that is, make `(april "1↑'amy'")` evaluate to `#(#\a)` 
and in general never evaluate an expression to a SIMPLE-ARRAY CHARACTER and instead always evaluate to at least SIMPLE-VECTOR.

then april would be consistent everywhere, right?
