### ISSUE TITLE
LispWorks listener: (april (test)) does not show everything in UTF-8

### ISSUE THREAD

**Issue by lispm** [phantomics/april#2]
Example:

```
â Printed: Catenated character and numeric arrays.
  _ (⍪⍳3),(3 3⍴'abcdef'),(3 3⍴⍳9),(3 3⍴'defghi'),⍪⍳3
  â "1 abc 1 2 3 def 1
      2 def 4 5 6 ghi 2
      3 abc 7 8 9 def 3
      " is expected to be "1 abc 1 2 3 def 1
      2 def 4 5 6 ghi 2
      3 abc 7 8 9 def 3
      " 

```

**Comment by phantomics** [comment]
This is an issue with the Prove testing library; it is responsible for printing the ✓ and × characters which get garbled for some reason. I have filed an issue with the Prove repository:

https://github.com/fukamachi/prove/issues/58

**Comment by phantomics** [comment]
I've just tested April with LispWorks 7.1.0 and it appears that this problem is gone; it must have been a problem with LW's handling of Unicode characters. I'm closing this but feel free to reopen if you see any remaining problems with April under LispWorks.

Also, LW 7.1.0 compiled April out of the box without needing the custom config described at https://github.com/phantomics/april/blob/master/lispworks-howto.md. Those instructions may be deprecated for newer versions of LW.
