### ISSUE TITLE
Evading Quicklisp.

### ISSUE THREAD

**Issue by jaccarmac** [phantomics/april#224]
I'm working on updating the version of April I packaged for Guix to 1.0. Guix doesn't support Quicklisp, so the use of that library in `install-demos` is making the build choke. Is the dependency on Quicklisp necessary or is ASDF sufficient to load the demos as in `load-demos`?

The issue I'm encountering is already touched on in #223, but I figure this is a distinct enough issue/request.

**Comment by Le-Brut** [comment]
+1 on this, I skimmed through the code but didn't understand the purpose of this new dependency, it might have been meant for the ncurses demo.

Also, it looks pretty dangerous how all those packages are :used, this could easily backfire if you ask me.

**Comment by phantomics** [comment]
The Quicklisp dependency is now removed. The libraries don't need it since they require no packages but April, only the demos do, and now users are directed to manually quickload the demos. Let me know how Guix packaging works.

Le-Brut, are you saying it would be better to import individual symbols from those packages?

**Comment by Le-Brut** [comment]
> The Quicklisp dependency is now removed.

Thank you!

> Le-Brut, are you saying it would be better to import individual symbols from those packages?

@phantomics Definitely. If one of the packages were to introduce a new symbol that another package already exports, or one that your package has, things will break on version upgrade. The only safe package I know of is alexandria, since they have a policy of introducing all new symbols into alexandria-1, alexandria-2 etc for this exact reason as so many people are :use'ing it.

**Comment by jaccarmac** [comment]
> Let me know how Guix packaging works.

I'll finish up the patch for the new version and see if I run into any problems further exploring the demos. In the meantime [the patchset to get it into the tree is here](https://issues.guix.gnu.org/52387). It didn't involve much funkiness at all.

**Comment by phantomics** [comment]
@Le-Brut the `(:use)` of packages has been curtailed. I'm closing this issue but feel free to reopen it if there are any further issues with Guix.
