### ISSUE TITLE
enclose does not always work on simple character scalars

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#23]
it works on character vectors
```
CL-USER> (april-p "⊂'hi'")
 hi 
#("hi")
```

but not with a simple scalar (that is a character).
```
CL-USER> (april-p "⊂'h'")
The value
  #\h
is not of type
  NUMBER
when binding SB-KERNEL::X
   [Condition of type TYPE-ERROR
```

in dyalog 
```
⊂'v'='v'
```
evaluates to 1. so enclose on a simple scalar is like an identity function.

but interestingly april does the right thing here:
```
CL-USER> (april-p "⊂'h'='h'")
1
1
```

**Comment by phantomics** [comment]
Actually, the problem you were having came from printing the output with `(april-p)`. I forgot to include a condition for the printer to handle scalar characters. It's fixed now.

One other thing: your code above has a problem. Since APL evaluates from right to left, when you enter `⊂'h'='h'"` the `'h'='h'` part is evaluated before the `⊂`, so you're just getting a scalar 1 and enclosing it. To do what you want you should enter `(⊂'h')='h'`.

One last thing: it's better to print with `(april-f)` instead of `(april-p)` because `(april-p)` could be confused for some kind of predicate function. It was the original name for the printing macro and I'm only leaving it in for the sake of backwards compatibility.
