### ISSUE TITLE
not exactly an issue -- just a discussion point

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#31]
hey, have you seen https://github.com/cbaggers/varjo ?
```
Varjo is a Lisp to GLSL compiler.
```

i know you said in your video on april that sending data over to the gpu is some overhead that probably makes doing so not worth it. but i am just curious what you think about the feasibility of using varjo on the lisp that april writes.

also, since this probably isn't the best place for discussion... do you have a place where we can discuss april in the open?

**Comment by phantomics** [comment]
Do you use IRC? Let's talk on freenode at ##phantomics if so. Otherwise what options do you like?

I've looked into Varjo and CEPL, CEPL has many tools for working with GPU arrays but it's intended to be kind of a graphical workstation so I'm not sure if I want to link it to April, Varjo seems like a better candidate since it's intended as more of a modular system focused on doing one thing. However, I haven't been able to get Varjo's examples working, I get a "vec4 is not a function" error. Have you been able to get Varjo working?

**Comment by justin2004** [comment]
should we update the readme to include the IRC channel in case anyone else wants to join the discussion?

**Comment by phantomics** [comment]
Sure, the channel is now in the readme.
