### ISSUE TITLE
possibility to compile to javascript?

### ISSUE THREAD

**Issue by cannadayr** [phantomics/april#4]
not really an issue, but a question.

Really interesting project. I see you also do projects in parenscript. I am not very familiar with the common lisp ecosystem (or limitations), is it theoretically possible to output the compiled lisp as javascript using parenscript?

**Comment by phantomics** [comment]
That's not possible with Parenscript, Parenscript is a Lisp dialect that compiles to Javascript. It doesn't compile arbitrary Lisp code to JS, you write your code in the specific Parenscript dialect and then it gets converted to JS; it does allow you to use macros giving immense power at compile time, but at runtime it's the same as any other JS.

There are Lisp dialects that aim for compilation to JS, such as [JSCL](https://github.com/jscl-project/jscl) and [sLip](http://lisperator.net/slip/). I haven't run April with them but you're welcome to try and let me know how it works. JS is not a very good language for implementing APL because it has no true multidimensional arrays; only nested vectors. There's also no support for array displacement, no native complex numbers and some other mathematical deficiencies. You could use special classes to fill some of the gaps, write something that behaves like a multidimensional array, etc., but performance will suffer.

What kind of application do you have in mind? I'd like to write a web REPL for April at some point, I've already used it to drive a browser-based voxel environment as seen [here](https://vimeo.com/269495385) at timestamp 09:47.

**Comment by cannadayr** [comment]
ahh yes thats what I thought. Might give it a shot if I need a break from something else.

I've been experimenting w/ erlang + gnu apl on the server side, and was considering complimentary client side technologies.

Nothing serious (yet) - mostly for my own benefit (or detriment). Initial ideas included time series based analysis.

Thanks!

**Comment by phantomics** [comment]
Sure thing, let me know if you give it a try.
