### ISSUE TITLE
Wrong output of Circular function

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#42]
April:

```lisp
(april:april-p` "
0 ¯1 ¯2 ¯6 ¯7 ∘.○ ¯2 ¯2J0
")
 2.236068              2.236068            
¯1.5707964J1.3169578  ¯1.5707964J1.3169578 
 3.1415927J¯1.3169578  3.1415927J¯1.3169578
 1.3169578J3.1415927   1.3169578J3.1415927 
¯0.54930615J1.5707964 ¯0.54930615J1.5707964
#2A((2.236068 2.236068)
    (#C(-1.5707964 1.3169578) #C(-1.5707964 1.3169578))
    (#C(3.1415927 -1.3169578) #C(3.1415927 -1.3169578))
    (#C(1.3169578 3.1415927) #C(1.3169578 3.1415927))
    (#C(-0.54930615 1.5707964) #C(-0.54930615 1.5707964)))
```

Some other APL:

```apl
      0 ¯1 ¯2 ¯6 ¯7 ∘.○ ¯2 ¯2J0
 0.0000000000J01.732050808  0.0000000000J01.732050808
¯1.5707963270J01.316957897 ¯1.5707963270J01.316957897
 3.1415926540J¯1.316957897  3.1415926540J¯1.316957897
 1.3169578970J03.141592654  1.3169578970J03.141592654
¯0.5493061443J¯1.570796327 ¯0.5493061443J¯1.570796327
```

**Comment by egao1980** [comment]
Please note the first line

**Comment by egao1980** [comment]
Another case:

```lisp
(april:april "¯4 ¯3 ∘.○ 1 1J0")
; Debugger entered on #<DIVISION-BY-ZERO {10081CF0F3}>
```

**Comment by egao1980** [comment]
```lisp
 (april:april-p "8 ○ 1 1J0")
0J1.7320508 0J1.7320508
#(#C(0.0 1.7320508) #C(0.0 1.7320508))
```

Expected:

```apl
      8 ○ 1 1J0
0J1.414213562 0J1.414213562
```

**Comment by phantomics** [comment]
Oops, I transcribed those functions in the early days of April and I forgot that `*` means exponent and not multiplication in APL. That's why I prefer the `⋆` star character for that function. I've updated the functions and now most should be correct.

I'm leaving this open for the time being because I noticed that my output was inconsistent with Dyalog's, and then I noticed that Dyalog's arctanh function (index ¯7) seems to be inconsistent with others.

```
In Dyalog:
      ¯7○¯2
0.5493061443J¯1.570796327

In GNU APL:
      ¯7○¯2
¯0.5493061443J1.570796327

In Common Lisp:
* (atanh -2)
#C(-0.54930615 1.5707964)

In Wolfram Alpha:
arctanh(-2)

Decimal approximation:

-0.54930614433405484569762261846126285232374527891137472586734716... +
1.5707963267948966192313216916397514420985846996875529104874722... i
```

Once I have an idea which implementation is correct I'll call this closed.

**Comment by egao1980** [comment]
let's follow GNU APL / Wolfram as we can access GNU APL test cases and it would be easier to check

**Comment by justin2004** [comment]
i'm interested to hear what the dyalog people say about that.

**Comment by phantomics** [comment]
Not a peep from Dyalog, but in other discussions I've started people are citing [this section](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node129.html#BRANCHCUTSSECTION) from the CLtL standard. It cites a SIGAPL paper written in 1981 for recommendations on the proper output of irrational functions that can have multiple valid outputs in the complex domain. 

Functions like arctanh can have multiple valid outputs; the tanh of the number above will be about -2 whether or not the imaginary part is negative, but the '81 paper recommends a consistent standard for implementing the funciton. That's the standard that CL, most APLs and J follow so that's the one I'm going with. Not sure why Dyalog works differently.
