### ISSUE TITLE
dyadic ⍳ with matrix on left

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#64]
i thought i read in the tutorial that the left argument must be a vector but then:
```
      (3 3⍴'CATRATDOG')⍳'RAT'
2
```

```
CL-USER> (april "(3 3⍴'CATRATDOG')⍳'RAT'")
The left argument to ⍳ must be a vector.
```

yeah, here is the snippet from the tutorial:
```
      (3 3⍴'CATRATDOG')⍳'RAT'
2
The left argument MUST be a vector. 
```
talking out of both sides of its mouth!

**Comment by phantomics** [comment]
That's what I thought too. Checking further into dyadic `⍳`, it looks like an array left argument is broken down into vectors along its last axis, and then the right argument is broken down to vectors as well. If the last axes aren't the same length an error occurs, otherwise the comparison is done as if the two arrays were vectors of the sub-vectors they've been broken down to. This is now working.
