### ISSUE TITLE
escaping `'` in string?

### ISSUE THREAD

**Issue by LdBeth** [phantomics/april#8]
```
CL-USER> (april:april "'''T'")
NIL
CL-USER> (april:april "''T'")
"'T"
CL-USER> (april:april "'''")
#\'
CL-USER> (april:april "''''")
NIL
CL-USER> (april:april "\"''\"")
"''"
CL-USER> (april:april "'\\''")
"\\'"
```
This behavior is different from what we get from traditional APL.

**Comment by phantomics** [comment]
Currently you can use backslashes to escape quote characters as with Lisp strings, but I'll look into implementing double-escaped quotes as well.

**Comment by phantomics** [comment]
Double-escaped quotes are now implemented; April retains the ability to use either single or double quotes, which causes the code in your second-to-last example to return `''` instead of an error. The last example also still deviates from normative APL because of the ability to use backslashes to escape quotes.
