### ISSUE TITLE
variables in recursive functions

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#84]
```
      f←{⎕←a←⍵-1⋄ a≥0:a,f a⋄0 }
      f 5
4
3
2
1
0
¯1
4 3 2 1 0 0
```
but when you catenate a and f a it looks like a doesn't get evaluated until the last invocation of f:
```
APRIL> (april "f←{⎕←a←⍵-1⋄⎕←' '⋄ $[a≥0;a,f a;0]}")
#<CLOSURE (LAMBDA (⍵ &OPTIONAL ⍺)) {1003D04C6B}>
APRIL> (april "f 5")
4 3 2 1 0 ¯1
#(-1 -1 -1 -1 -1 0)
```

**Comment by phantomics** [comment]
This is a result of April variable calls in functions being dynamic rather than lexical. I'm planning to implement variable hoisting within functions which should fix this, but I have some other things to clear first like the function inverter.

**Comment by phantomics** [comment]
Variable hoisting is now working. It may take some trial and error to come up with a hoisting heuristic that covers all possible cases, so be on the lookout for bugs. 

```lisp
* (april-f "f←{⎕←a←⍵-1 ⋄ $[a≥0;a,f a;0]} ⋄ f 5")
4
3
2
1
0
¯1
4 3 2 1 0 0
#(4 3 2 1 0 0)
```

I've also corrected the printing of scalar values so that a newline is always printed afterward, as in other APLs. The `⎕←' '` is no longer needed.

If you evaluate `(april (with (:compile-only)) "f←{⎕←a←⍵-1 ⋄ $[a≥0;a,f a;0]} ⋄ f 5")`, you'll see there's a form starting with `(LET ((𝕊|a|))` enclosing the function code. That marks `a` as a lexical variable.

Let me know how it works for you.
