### ISSUE TITLE
april permits vectors of non-nested character vectors

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#90]
in dyalog you have to explicitly disclose the character vector
```
      inp←'apple' 'pasta'
      ⍴inp[1]

      ⍴⊃inp[1]
5
```

but april allows the items of the vector to not be enclosed:
```
APRIL> (april-c "{⍴⍵[1]}"
         (vector "apple" "pasta") )
#(5)
```

but april does the right thing if you make the vectors with APL:
```
APRIL> (april "inp←'apple' 'pasta'
        ⍴inp[1]" )
#()
APRIL> (april "⍴⊃inp[1]")
#(5)
```

**Comment by phantomics** [comment]
Good catch, you're passing data into April from outside and it doesn't comprehensively check those arrays to ensure they're APL-appropriate. I need to think about the right way to implement that because it would slow the language down considerably if any t-type array passed from outside had to be combed through to find non-enclosed nested arrays. What if you were passing massive arrays in and every one needed to be checked?

I'm thinking there will be an option to "correct" input. I've also been planning a function to un-nest output arrays, which will synergize with this task.

**Comment by justin2004** [comment]
> What if you were passing massive arrays in and every one needed to be checked?

yeah, it might be fine to allow non-enclosed character vectors if it is faster for massive arrays. the only reason i opened the issue was because i noticed one of my solutions for advent of code wouldn't run in dyalog because i had a vectors of non-enclosed character vectors.

**Comment by phantomics** [comment]
April now includes a function called `(apl-format-array)`. It works like this:

```lisp
* (apl-format-array (vector "abc" "def"))
#(#0A"abc" #0A"def")
```

All nested arrays are converted to an APL-compatible format. Also, `(april)` has a new option:

```lisp
* (april-f (with (:state :unformat-output t)) "2 2⍴⊂2 2⍴⍳4")
 1 2  1 2
 3 4  3 4
 1 2  1 2
 3 4  3 4
#2A((#2A((1 2) (3 4)) #2A((1 2) (3 4))) (#2A((1 2) (3 4)) #2A((1 2) (3 4))))
```

Now you can remove the APL-required nesting when data is output back to CL. I'll be testing these functions some more and them documenting them in the README.

**Comment by justin2004** [comment]
nice! i'll be using this straight away!

**Comment by phantomics** [comment]
New documentation of these features is up: 

https://github.com/phantomics/april#differences-between-apl-and-common-lisp-nested-array-models

https://github.com/phantomics/april#unformat-output
