### ISSUE TITLE
⎕IO does not persist -- just a question

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#91]
```
APRIL> (april "⎕IO←0")
0
APRIL> (april "⎕IO")
1
```

but non-system variables are persistent across invocations.
and even some system variables are:
```
APRIL> (april "⎕D←⎕D,'a'")
"0123456789a"
APRIL> (april "⎕D")
"0123456789a"
```

and in dyalog it does persist, of course.

what is the thinking here?

**Comment by phantomics** [comment]
It used to persist if you invoked April with `(april (with (:state :index-origin 0)) "⍳9")`. After doing that, `(april "⍳9")` would still start from 0 when using the same workspace. However, the change to the workspace system eliminated that feature. I decided that assigning `⎕IO` would only affect the current expression because I thought that assigning `⎕IO` made more sense as a transient configuration option. However, this is not in line with APL standards so I'll make `⎕IO` persistent as in other implementations.

**Comment by justin2004** [comment]
the current way seems nice if you want to do things like:
```
(bt:make-thread #'(lambda ()
                    (april "⍳10")))
```

i wonder how dyalog's spawn (multiple threads) handles having a global ⎕IO ?

**Comment by phantomics** [comment]
I've revised the system for handling `⎕IO` and `⎕PP`. [Read about it here.](https://github.com/phantomics/april#about-workspace-variables-index-origin-and-print-precision) Long story short, `⎕IO` and `⎕PP` can be assigned to create persistent changes, but you can also pass `:index-origin` and `:print-precision` parameters to an April invocation and they will affect only the code passed to that invocation. This should be a good solution for the parallel use case you describe.

**Comment by justin2004** [comment]
excellent!
